# Generated by Django 4.2.7 on 2023-11-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuario", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Usuarios", new_name="Usuario",),
    ]
